server:
  port: 8885

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/le_back_end?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

